import "./globals.css";

export const metadata = {
  title: "Desainego",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/favicon_desainego.svg',
        type: 'image/svg+xml',
      }
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
